name: update_controls

on:
  push:

jobs:
  linux:
    name: Update controls file
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8.x]
    steps:
    - uses: actions/checkout@v1
    - name: Make executeable
      run: chmod +x ./localizable.sh
    - name: script
      run: ./prepare_update.sh
      shell: bash
